# Generated by Django 5.2.3 on 2025-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('regular_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('descriptions', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('category', models.CharField(choices=[('F', 'Fruits'), ('V', 'Vegetable'), ('DF', 'Dryfruits'), ('M', 'meat'), ('FH', 'Fish')], max_length=2)),
            ],
        ),
    ]
