# Generated by Django 5.2.7 on 2025-10-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userprofile_user_order_orderitem_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
